### PR TITLE
Testing latest version

### PR DESCRIPTION
**Pull request by wildsm**
Updating example for the latest bandframework release

### CODE REVIEW

**Comment by wildsm** [comment]
Will need to update the example:

```
$ python parmoo_fayans_test.py --comms local --nworkers 4
Traceback (most recent call last):
  File "/home/wild/oldcomp/repos/parmoo-solver-farm/fayans-model-calibration-2022/parmoo_fayans_test.py", line 20, in <module>
    from parmoo.extras.libe import libE_MOOP
  File "/home/wild/.local/lib/python3.10/site-packages/parmoo/__init__.py", line 14, in <module>
    from .moop import MOOP
  File "/home/wild/.local/lib/python3.10/site-packages/parmoo/moop.py", line 21, in <module>
    from parmoo.embeddings.default_embedders import ContinuousEmbedder,  \
ModuleNotFoundError: No module named 'parmoo.embeddings'

```

**Comment by thchang** [comment]
I'm not sure what we want to do here.  I like keeping some of these static (hence why I locked the version numbers in the subdirectories) as snapshots in time.  Additionally, the two existing directories are referenced by the design paper and so are linked to the version of ParMOO used to run those experiments.

We could either:
 - Update these examples, in which case someone needs to re-run the experiments for the design paper (someone being you, I no longer have access to those machines)
 - Create another Band example directory which we do update to match the BAND version (you'll have to update the BAND docs to reference this)

**Comment by thchang** [comment]
@wildsm

**Comment by wildsm** [comment]
@thchang Good point. I agree that we should not update the `results` so that things are static for the problem definition.

One could create a nearly similar (lighter since it doesn't need `results`?) directory to track newer version(s)... this is especially helpful with API-breaking changes.

We can do this in this PR.

**Comment by wildsm** [comment]
The current (using 4.1) error is

```
$ python3 parmoo_fayans_test.py --comms local --nworkers 4
Traceback (most recent call last):
  File "/home/wild/oldcomp/repos/parmoo-solver-farm/fayans-model-calibration-2024/parmoo_fayans_test.py", line 21, in <module>
    from parmoo.optimizers import TR_LBFGSB
ImportError: cannot import name 'TR_LBFGSB' from 'parmoo.optimizers' (/home/wild/.local/lib/python3.10/site-packages/parmoo/optimizers/__init__.py)
```

@thchang - can you maybe look at `fayans-model-calibration-2024/`?

**Comment by thchang** [comment]
I think the hotfix in `parmoo 0.4.1` should fix the packaging issue you were having.

However, I will need to update several items for the interface-breaking changes introduced in `0.4.0`

I will do so later today or tomorrow.

**Comment by thchang** [comment]
@wildsm , sorry I missed your comment -- yes, that is expected.  I changed the naming of many of the solver components to consolidate redundant code and create a consistent naming convention.  I tried to create aliases to maintain backward compatibility, but it's not always possible.

Also, other interface-breaking changes will cause issues, such as providing a separate gradient evaluation function instead of a gradient option in the objective.

I'll sit down and fix it later today.

**Review by thchang — APPROVED** [review]
@wildsm I updated the scripts and the test runs on my laptop now and does not error out.

The other 2 scripts appear to work, but I had to kill them after an hour because I don't have access to compute anymore.  If you want to be sure, you'd need to detach them on a dedicated machine.  Also, someone should inspect the results to make sure they look OK.

I'll leave it up to you whether you want to do that.

**Comment by wildsm** [comment]
@thchang - I 'm still having trouble 

`parmoo-solver-farm/fayans-model-calibration-2024$ python3 -m pip install -r REQUIREMENTS.txt
`
succeeds

`parmoo-solver-farm/fayans-model-calibration-2024$ python3 parmoo_fayans_test.py --comms local --nworkers 4
`
yields:

```
Traceback (most recent call last):
  File "/home/wild/oldcomp/repos/parmoo-solver-farm/fayans-model-calibration-2024/parmoo_fayans_test.py", line 89, in <module>
    fayans_moop.solve(sim_max=200, wt_max=600)
  File "/home/wild/.local/lib/python3.10/site-packages/parmoo/extras/libe.py", line 800, in solve
    H, persis_info, flag = libE(sim_specs, gen_specs, exit_criteria,
  File "/home/wild/.local/lib/python3.10/site-packages/libensemble/libE.py", line 232, in libE
    return libE_funcs[comms_type](sim_specs, gen_specs, exit_criteria, persis_info, alloc_specs, libE_specs, H0)
  File "/home/wild/.local/lib/python3.10/site-packages/libensemble/libE.py", line 422, in libE_local
    check_inputs(libE_specs, alloc_specs, sim_specs, gen_specs, exit_criteria, H0)
  File "/home/wild/.local/lib/python3.10/site-packages/libensemble/tools/check_inputs.py", line 227, in check_inputs
    check_libE_specs(libE_specs, serial_check)
  File "/home/wild/.local/lib/python3.10/site-packages/libensemble/tools/check_inputs.py", line 37, in check_libE_specs
    assert k in allowed_libE_spec_keys, "Key %s is not allowed in libE_specs. Supported keys are: %s " % (
AssertionError: Key final_gen_send is not allowed in libE_specs. Supported keys are: ['abort_on_exception', 'enforce_worker_core_bounds', 'authkey', 'disable_resource_manager', 'dedicated_mode', 'comms', 'resource_info', 'disable_log_files', 'final_fields', 'ip', 'kill_canceled_sims', 'mpi_comm', 'num_resource_sets', 'nworkers', 'port', 'profile', 'safe_mode', 'save_every_k_gens', 'save_every_k_sims', 'save_H_and_persis_on_abort', 'scheduler_opts', 'use_persis_return_gen', 'use_persis_return_sim', 'workerID', 'worker_timeout', 'zero_resource_workers', 'worker_cmd', 'ensemble_copy_back', 'ensemble_dir_path', 'use_worker_dirs', 'sim_dirs_make', 'sim_dir_copy_files', 'sim_dir_symlink_files', 'sim_input_dir', 'gen_dirs_make', 'gen_dir_copy_files', 'gen_dir_symlink_files', 'gen_input_dir'] 
```
so maybe an issue with an OLD libEnsemble being used?

**Comment by thchang** [comment]
@wildsm it looks like you have an older version of libensemble -- you need libensemble>=1.0.0

Maybe we add this to the `REQUIREMENTS.txt` file in this repo?

I have it set as the version in the parmoo repo's `REQUIREMENTS.txt`, but it looks like we don't pin the version requirements in ParMOO's `setup.py` file 🫤

**Comment by wildsm** [comment]
Yes, that's exactly it, the `parmoo[extras]==0.4.1` was insufficient since the minimum libensemble version wasn't pull in via setup. Thanks for opening [#107.](https://github.com/parmoo/parmoo/issues/107)

**Comment by wildsm** [comment]
Note that this new directory will be referenced in the next BAND release (see https://github.com/bandframework/bandframework/tree/release/parmoo_v0.4/software/parmoo)

**Pull request merged**
